apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthscore-processor
  namespace: production
  labels:
    app: healthscore-processor
    tier: backend
    type: microservice
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      service: healthscore-processor
  template:
    metadata:
      labels:
        app: healthscore-processor
        service: healthscore-processor
    spec:
      containers:
        - name: healthscore-processor
          image: medicihealthscore.azurecr.io/healthscore-processor:#{Build.BuildNumber}#
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1280Mi
          volumeMounts:
            - name: processor-appsettings-secret
              mountPath: /app/HealthScore.Processor/appsettings.Production.json
              subPath: appsettings.Production.json
      volumes:
        - name: processor-appsettings-secret
          secret:
            secretName: processor-appsettings-production
---
apiVersion: v1
kind: Service
metadata:
  name: healthscore-processor
  namespace: production
  labels:
    app: healthscore-processor
    service: healthscore-processor
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: healthscore-processor